// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPnJoTyGQnAEH5SyulZLRwpsLJz6pUStc',
    appId: '1:301441016374:web:a86dca6320e534944c6e97',
    messagingSenderId: '301441016374',
    projectId: 'findid',
    authDomain: 'findid.firebaseapp.com',
    storageBucket: 'findid.appspot.com',
    measurementId: 'G-V5JHW4ZDE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTi2BMYRHlXzpk24Z1kY6OCGaAcn_B4oU',
    appId: '1:301441016374:android:e2583ccf01a960704c6e97',
    messagingSenderId: '301441016374',
    projectId: 'findid',
    storageBucket: 'findid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK8PfvHMCDY_xV6holtrglgloHWl5nDc0',
    appId: '1:301441016374:ios:76045d9cd744fcb84c6e97',
    messagingSenderId: '301441016374',
    projectId: 'findid',
    storageBucket: 'findid.appspot.com',
    iosClientId: '301441016374-pjjvmbahltvuq0r7a2ir8161fd64e34a.apps.googleusercontent.com',
    iosBundleId: 'com.example.findMyId',
  );
}
